version: "3"

services:
  web:
    build: .
#    command: gunicorn --bind 0.0.0.0:5000 app:app
#    command: bash -c "alembic upgrade head"
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app/

    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sales
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  database-data: