"""Added account table

Revision ID: ba8994c3eba0
Revises: c605e02d3852
Create Date: 2020-10-11 13:15:56.103526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8994c3eba0'
down_revision = 'c605e02d3852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
